//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vampire.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vampire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        internal static string ActionBuild {
            get {
                return ResourceManager.GetString("ActionBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action lets the AI build a unit of the specified type. 的本地化字符串。
        /// </summary>
        internal static string ActionBuildDesc {
            get {
                return ResourceManager.GetString("ActionBuildDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit To Build 的本地化字符串。
        /// </summary>
        internal static string ActionBuildUnitType {
            get {
                return ResourceManager.GetString("ActionBuildUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of unit which will be built. 的本地化字符串。
        /// </summary>
        internal static string ActionBuildUnitTypeDesc {
            get {
                return ResourceManager.GetString("ActionBuildUnitTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Closest 的本地化字符串。
        /// </summary>
        internal static string ActionFocusClosest {
            get {
                return ResourceManager.GetString("ActionFocusClosest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unit will focus the closest object of the given type. 的本地化字符串。
        /// </summary>
        internal static string ActionFocusClosestDesc {
            get {
                return ResourceManager.GetString("ActionFocusClosestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit To Focus 的本地化字符串。
        /// </summary>
        internal static string ActionFocusClosestUnitType {
            get {
                return ResourceManager.GetString("ActionFocusClosestUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the units which will be considered to be focused. 的本地化字符串。
        /// </summary>
        internal static string ActionFocusClosestUnitTypeDesc {
            get {
                return ResourceManager.GetString("ActionFocusClosestUnitTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Focus 的本地化字符串。
        /// </summary>
        internal static string ActionFollowFocus {
            get {
                return ResourceManager.GetString("ActionFollowFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unit will follow the focused object. If no object is focused, the action fails. 的本地化字符串。
        /// </summary>
        internal static string ActionFollowFocusDesc {
            get {
                return ResourceManager.GetString("ActionFollowFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inherit Focus 的本地化字符串。
        /// </summary>
        internal static string ActionInheritFocus {
            get {
                return ResourceManager.GetString("ActionInheritFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unit will focus the focus of its focus. 的本地化字符串。
        /// </summary>
        internal static string ActionInheritFocusDesc {
            get {
                return ResourceManager.GetString("ActionInheritFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Until Focus Is In Range 的本地化字符串。
        /// </summary>
        internal static string ActionMoveTillFocusIsInRange {
            get {
                return ResourceManager.GetString("ActionMoveTillFocusIsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unit moves towards the object is has focused and stops if it comes in attack/build range. 的本地化字符串。
        /// </summary>
        internal static string ActionMoveTillFocusIsInRangeDesc {
            get {
                return ResourceManager.GetString("ActionMoveTillFocusIsInRangeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Oxygen From Focus 的本地化字符串。
        /// </summary>
        internal static string ActionTransferOxygenFromFocus {
            get {
                return ResourceManager.GetString("ActionTransferOxygenFromFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action transfers oxygen from the focused object into the units cargo. 的本地化字符串。
        /// </summary>
        internal static string ActionTransferOxygenFromFocusDesc {
            get {
                return ResourceManager.GetString("ActionTransferOxygenFromFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Oxygen To Focus 的本地化字符串。
        /// </summary>
        internal static string ActionTransferOxygenToFocus {
            get {
                return ResourceManager.GetString("ActionTransferOxygenToFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oxygen is transferred from the units cargo to the focused object. 的本地化字符串。
        /// </summary>
        internal static string ActionTransferOxygenToFocusDesc {
            get {
                return ResourceManager.GetString("ActionTransferOxygenToFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攻击 的本地化字符串。
        /// </summary>
        internal static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择最远的技能 的本地化字符串。
        /// </summary>
        internal static string ChooseFarthestSkill {
            get {
                return ResourceManager.GetString("ChooseFarthestSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择随机技能 的本地化字符串。
        /// </summary>
        internal static string ChooseRandomSkill {
            get {
                return ResourceManager.GetString("ChooseRandomSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择视野内玩家作为目标 的本地化字符串。
        /// </summary>
        internal static string ChooseTargetInView {
            get {
                return ResourceManager.GetString("ChooseTargetInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择攻击者作为目标 的本地化字符串。
        /// </summary>
        internal static string ChooseTargetWhoAttack {
            get {
                return ResourceManager.GetString("ChooseTargetWhoAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cargo Is Full 的本地化字符串。
        /// </summary>
        internal static string ConditionCargoIsFull {
            get {
                return ResourceManager.GetString("ConditionCargoIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if the cargo of the unit is completely full. 的本地化字符串。
        /// </summary>
        internal static string ConditionCargoIsFullDesc {
            get {
                return ResourceManager.GetString("ConditionCargoIsFullDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Is 的本地化字符串。
        /// </summary>
        internal static string ConditionFocusIs {
            get {
                return ResourceManager.GetString("ConditionFocusIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checks if the currently focused object is of the specified type. 的本地化字符串。
        /// </summary>
        internal static string ConditionFocusIsDesc {
            get {
                return ResourceManager.GetString("ConditionFocusIsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Type 的本地化字符串。
        /// </summary>
        internal static string ConditionFocusIsUnitType {
            get {
                return ResourceManager.GetString("ConditionFocusIsUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This condition is true if the focused unit is of this type. 的本地化字符串。
        /// </summary>
        internal static string ConditionFocusIsUnitTypeDesc {
            get {
                return ResourceManager.GetString("ConditionFocusIsUnitTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Less Than 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThan {
            get {
                return ResourceManager.GetString("ConditionHasLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Count 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThanCount {
            get {
                return ResourceManager.GetString("ConditionHasLessThanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This condition is true if the layer has less than this many units of the given type. 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThanCountDesc {
            get {
                return ResourceManager.GetString("ConditionHasLessThanCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This condition is true if the AI has less than n units of the specified type. 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThanDesc {
            get {
                return ResourceManager.GetString("ConditionHasLessThanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Type 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThanUnitType {
            get {
                return ResourceManager.GetString("ConditionHasLessThanUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the units which are counted. 的本地化字符串。
        /// </summary>
        internal static string ConditionHasLessThanUnitTypeDesc {
            get {
                return ResourceManager.GetString("ConditionHasLessThanUnitTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Needle With Less Servants Than 的本地化字符串。
        /// </summary>
        internal static string ConditionHasNeedleWithLessServantsThan {
            get {
                return ResourceManager.GetString("ConditionHasNeedleWithLessServantsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This condition is true if the AI has a needle with less than n transporters assigned to it. If four transporters are assigned to a needle, it is fully charged. 的本地化字符串。
        /// </summary>
        internal static string ConditionHasNeedleWithLessServantsThanDesc {
            get {
                return ResourceManager.GetString("ConditionHasNeedleWithLessServantsThanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servants 的本地化字符串。
        /// </summary>
        internal static string ConditionHasNeedleWithLessServantsThanServants {
            get {
                return ResourceManager.GetString("ConditionHasNeedleWithLessServantsThanServants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This condition is true if any of the player&apos;s needles has less than n suppliers. 的本地化字符串。
        /// </summary>
        internal static string ConditionHasNeedleWithLessServantsThanServantsDesc {
            get {
                return ResourceManager.GetString("ConditionHasNeedleWithLessServantsThanServantsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoop {
            get {
                return ResourceManager.GetString("DecoratorLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopCount {
            get {
                return ResourceManager.GetString("DecoratorLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines how often the child will be called. If the child fails, the loop is aborted and fails. 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopCountDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator calls its child n times. 的本地化字符串。
        /// </summary>
        internal static string DecoratorLoopDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string DecoratorNot {
            get {
                return ResourceManager.GetString("DecoratorNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator inverts the return value of the attached node. If the attached node fails, it will appear as it has succedded and vice versa. 的本地化字符串。
        /// </summary>
        internal static string DecoratorNotDesc {
            get {
                return ResourceManager.GetString("DecoratorNotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful 的本地化字符串。
        /// </summary>
        internal static string DecoratorTrue {
            get {
                return ResourceManager.GetString("DecoratorTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This decorator lets it child appear to be valid, even if it fails. 的本地化字符串。
        /// </summary>
        internal static string DecoratorTrueDesc {
            get {
                return ResourceManager.GetString("DecoratorTrueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束战斗 的本地化字符串。
        /// </summary>
        internal static string EndFight {
            get {
                return ResourceManager.GetString("EndFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Destroyed 的本地化字符串。
        /// </summary>
        internal static string EventFocusDestroyed {
            get {
                return ResourceManager.GetString("EventFocusDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node becomes active if the focus of the unit was destroyed. 的本地化字符串。
        /// </summary>
        internal static string EventFocusDestroyedDesc {
            get {
                return ResourceManager.GetString("EventFocusDestroyedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Unit Type 的本地化字符串。
        /// </summary>
        internal static string EventFocusDestroyedType {
            get {
                return ResourceManager.GetString("EventFocusDestroyedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the focused unit which needs to be destroyed to trigger this event. 的本地化字符串。
        /// </summary>
        internal static string EventFocusDestroyedTypeDesc {
            get {
                return ResourceManager.GetString("EventFocusDestroyedTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Built 的本地化字符串。
        /// </summary>
        internal static string EventUnitBuilt {
            get {
                return ResourceManager.GetString("EventUnitBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node is enabled if a unit of the specified type is built. 的本地化字符串。
        /// </summary>
        internal static string EventUnitBuiltDesc {
            get {
                return ResourceManager.GetString("EventUnitBuiltDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Built Unit Type 的本地化字符串。
        /// </summary>
        internal static string EventUnitBuiltType {
            get {
                return ResourceManager.GetString("EventUnitBuiltType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the unit which needs to be built to trigger this event. 的本地化字符串。
        /// </summary>
        internal static string EventUnitBuiltTypeDesc {
            get {
                return ResourceManager.GetString("EventUnitBuiltTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Destroyed 的本地化字符串。
        /// </summary>
        internal static string EventUnitDestroyed {
            get {
                return ResourceManager.GetString("EventUnitDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node becomes active if a unit of the specified type was destroyed. 的本地化字符串。
        /// </summary>
        internal static string EventUnitDestroyedDesc {
            get {
                return ResourceManager.GetString("EventUnitDestroyedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroyed Unit Type 的本地化字符串。
        /// </summary>
        internal static string EventUnitDestroyedType {
            get {
                return ResourceManager.GetString("EventUnitDestroyedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the unit which needs to be destroyed to trigger this event. 的本地化字符串。
        /// </summary>
        internal static string EventUnitDestroyedTypeDesc {
            get {
                return ResourceManager.GetString("EventUnitDestroyedTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有玩家在视野内 的本地化字符串。
        /// </summary>
        internal static string HasRoleInView {
            get {
                return ResourceManager.GetString("HasRoleInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否有目标 的本地化字符串。
        /// </summary>
        internal static string HasTarget {
            get {
                return ResourceManager.GetString("HasTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impulse 的本地化字符串。
        /// </summary>
        internal static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node is only visible when one of the associated events were fired. 的本地化字符串。
        /// </summary>
        internal static string ImpulseDesc {
            get {
                return ResourceManager.GetString("ImpulseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否被攻击 的本地化字符串。
        /// </summary>
        internal static string IsAttacked {
            get {
                return ResourceManager.GetString("IsAttacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop 的本地化字符串。
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string LoopCount {
            get {
                return ResourceManager.GetString("LoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定子结点的执行次数，如果子结点执行返回False，则中止循环。 的本地化字符串。
        /// </summary>
        internal static string LoopCountDesc {
            get {
                return ResourceManager.GetString("LoopCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环子结点n次 的本地化字符串。
        /// </summary>
        internal static string LoopDesc {
            get {
                return ResourceManager.GetString("LoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到攻击范围 的本地化字符串。
        /// </summary>
        internal static string MoveToAttackRange {
            get {
                return ResourceManager.GetString("MoveToAttackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        internal static string NodeGroupActions {
            get {
                return ResourceManager.GetString("NodeGroupActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composites 的本地化字符串。
        /// </summary>
        internal static string NodeGroupComposites {
            get {
                return ResourceManager.GetString("NodeGroupComposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        internal static string NodeGroupConditions {
            get {
                return ResourceManager.GetString("NodeGroupConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decorators 的本地化字符串。
        /// </summary>
        internal static string NodeGroupDecorators {
            get {
                return ResourceManager.GetString("NodeGroupDecorators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        internal static string NodeGroupEvents {
            get {
                return ResourceManager.GetString("NodeGroupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Impulses 的本地化字符串。
        /// </summary>
        internal static string NodeGroupImpulses {
            get {
                return ResourceManager.GetString("NodeGroupImpulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selectors 的本地化字符串。
        /// </summary>
        internal static string NodeGroupSelectors {
            get {
                return ResourceManager.GetString("NodeGroupSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequences 的本地化字符串。
        /// </summary>
        internal static string NodeGroupSequences {
            get {
                return ResourceManager.GetString("NodeGroupSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not 的本地化字符串。
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对子结点的返回值取反 的本地化字符串。
        /// </summary>
        internal static string NotDesc {
            get {
                return ResourceManager.GetString("NotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parallel 的本地化字符串。
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平行结点：并行执行多个子结点 的本地化字符串。
        /// </summary>
        internal static string ParallelDesc {
            get {
                return ResourceManager.GetString("ParallelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        internal static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择结点：依次执行子结点，直到某一子结点返回True；如果所有子节点都返回False，则返回False，否则返回True的 的本地化字符串。
        /// </summary>
        internal static string SelectorDesc {
            get {
                return ResourceManager.GetString("SelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Linear 的本地化字符串。
        /// </summary>
        internal static string SelectorLinear {
            get {
                return ResourceManager.GetString("SelectorLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node will call its attached nodes in the given order until one succeeds. If all attached nodes fail, this node fails, too. 的本地化字符串。
        /// </summary>
        internal static string SelectorLinearDesc {
            get {
                return ResourceManager.GetString("SelectorLinearDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序结点：依次执行子结点，直到某一子结点返回False；如果所有子节点都返回True，则返回True，否则返回False 的本地化字符串。
        /// </summary>
        internal static string SequenceDesc {
            get {
                return ResourceManager.GetString("SequenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence Linear 的本地化字符串。
        /// </summary>
        internal static string SequenceLinear {
            get {
                return ResourceManager.GetString("SequenceLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node will call its attached nodes in the given order. If any of the attached nodes fails, this node fails as well. 的本地化字符串。
        /// </summary>
        internal static string SequenceLinearDesc {
            get {
                return ResourceManager.GetString("SequenceLinearDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful 的本地化字符串。
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略子结点的返回值，总是返回True 的本地化字符串。
        /// </summary>
        internal static string SuccessfulDesc {
            get {
                return ResourceManager.GetString("SuccessfulDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n 的本地化字符串。
        /// </summary>
        internal static string UnitsCount {
            get {
                return ResourceManager.GetString("UnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sec 的本地化字符串。
        /// </summary>
        internal static string UnitsSeconds {
            get {
                return ResourceManager.GetString("UnitsSeconds", resourceCulture);
            }
        }
    }
}
